name: java microservice CI

on:
  push:
    branches:
      - main
#workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}
  TAG: ${{ vars.TAG }}
  STACK_NAME: ${{ vars.STACK_NAME }}

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MODULE_FULLNAME: ${{ vars.PROJECT_NAME }}/${{ vars.MODULE_NAME }}
      REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            java-pipeline/.elasticbeanstalk/config.yml
            java-pipeline/Dockerrun.aws.config.json

      - name: Build Docker image
        run: docker build -t $MODULE_FULLNAME $MODULE_NAME

      - name: Authenticate Docker to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $REGISTRY_URL

      - name: Push Docker image to AWS ECR
        run: docker push $REGISTRY_URL/$MODULE_FULLNAME:$TAG

#deploy:
#  runs-on: ubuntu-latest
#  needs: build
#
#  steps:
#    - name: Download artifact
#      uses: actions/download-artifact@v4
#      with:
#        name: ebconfig
#
#    - name: Replace placeholders in Dockerrun.aws.json
#      run: |
#        sed -i='' "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" Dockerrun.aws.json && \
#        sed -i='' "s/<PROJECT_NAME>/$PROJECT_NAME/" Dockerrun.aws.json && \
#        sed -i='' "s/<MODULE_NAME>/$MODULE_NAME/" Dockerrun.aws.json && \
#        sed -i='' "s/<TAG>/$TAG/" Dockerrun.aws.json
#
#    - name: Setup Python
#      uses: actions/setup-python@v3
#      with:
#        python-version: '3.10'
#
#    - name: Install AWS EB CLI
#      run: |
#        python -m pip install --upgrade pip
#        pip install awsebcli
#
#    - name: Deploy to AWS Elastic Beanstalk
#      run: |
#        eb deploy --verbose
